export const INITIAL_VALUE_CASE_FOR_FORM =
{
  uid: '',
  case_id: '',
  date: '',
  plaintiffLastname: '',
  plaintiffName: '',
  plaintiffSurname: '',
  plaintiffBirthday: '',
  plaintiffReg_address: '',
  plaintiffRes_address: '',
  plaintiffPhone: '',
  plaintiffInn: '',
  plaintiffOgrn: '',
  plaintiffCompany: '',
  plaintiffLegal_address: '',
  plaintiffMailing_address: '',
  plaintiffKpp: '',
  plaintiffPc: '',
  plaintiffBank: '',
  plaintiffBic: '',
  plaintiffKc: '',

  defendantLastname: '',
  defendantName: '',
  defendantSurname: '',
  defendantBirthday: '',
  defendantReg_address: '',
  defendantRes_address: '',
  defendantPhone: '',
  defendantInn: '',
  defendantOgrn: '',
  defendantCompany: '',
  defendantLegal_address: '',
  defendantMailing_address: '',
  defendantKpp: '',
  defendantPc: '',
  defendantBank: '',
  defendantBic: '',
  defendantKc: '',
}
export const phoneNumberMask = [
  "+",
  "7",
  " ",
  /[1-9]/,
  /\d/,
  /\d/,
  " ",
  /\d/,
  /\d/,
  /\d/,
  " ",
  /\d/,
  /\d/,
  /\d/,
  /\d/
];